export const constants = {
    TRAIN_WIDTH: 1381,
    TRAIN_HEIGHT: 93,
    BUILDING_CONFIGURATION: [
        {
            assetIndex: 0,
            bottom: 0,
            left: 0,
            zIndex: -1,
            width: 126,
            height: 641,
        },
        {
            assetIndex: 1,
            bottom: 0,
            left: 150,
            zIndex: -1,
            width: 98,
            height: 539,
        },
        {
            assetIndex: 3,
            bottom: 0,
            left: 300,
            zIndex: -1,
            width: 104,
            height: 428,
        },
        {
            assetIndex: 4,
            bottom: 0,
            left: 400,
            zIndex: -1,
            width: 127,
            height: 433,
        },
        {
            assetIndex: 6,
            bottom: 0,
            left: 500,
            zIndex: -1,
            width: 125,
            height: 437,
        },
        {
            assetIndex: 8,
            bottom: 0,
            left: 620,
            zIndex: -1,
            width: 159,
            height: 606,
        },
        {
            assetIndex: 9,
            bottom: 0,
            left: 750,
            zIndex: -1,
            width: 113,
            height: 628,
        },
        {
            assetIndex: 2,
            bottom: 0,
            left: 1350,
            zIndex: -1,
            width: 143,
            height: 412,
        },
        {
            assetIndex: 7,
            bottom: 30,
            left: 1430,
            zIndex: -2,
            width: 121,
            height: 613,
        },
        {
            assetIndex: 5,
            bottom: 0,
            left: 1600,
            zIndex: -1,
            width: 167,
            height: 410,
        },
    ],
};